### ISSUE TITLE
Is there any plan to upgrade this project to 5.1?

### ISSUE THREAD

**Issue by 902D9** [Ji-Rath/MassAITesting#5]
Hi. This project is very helpful for learning Mass AI. Thank you. But I had a lot of problems trying to upgrade it to 5.1 because of the API update. It took me a lot of time but I couldn't solve them all. So I would like to ask if you have a plan to update it to 5.1?

**Comment by Ji-Rath** [comment]
There is very slow progress to update to 5.3
You can view the current progress here: [https://github.com/Ji-Rath/MassAITesting/tree/UE5.3](UE5.3)

At its current state, a lot is broken and there are various crashes. I can't guarantee that I will finish soon as I have been busy lately but hopefully it points you in the right direction.

**Comment by 902D9** [comment]
Just take your time according to your own plan. Thank you for your project and work.
